project_id = "ututdskuykdosmbgjkzh"

[functions.generate-business-insights]
verify_jwt = false

[functions.extract-audit-insights]
verify_jwt = false

[functions.extract-invoice-data]
verify_jwt = false

[functions.send-report-pdf]
verify_jwt = false

[functions.generate-proposal]
verify_jwt = false

[functions.generate-contract]
verify_jwt = false

[functions.website-chatbot]
verify_jwt = false
